extends:
  - airbnb
  - plugin:flowtype/recommended
  - plugin:react/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
plugins:
  - react
  - jsx-a11y
  - import
  - flowtype
  - prettier
settings:
  import/resolver:
    babel-module: {}
parser: babel-eslint
rules:
  no-unused-expressions:
    - error
    - allowTernary: true
  prettier/prettier:
    - warn
    - singleQuote: true
      trailingComma: es5
  react/jsx-filename-extension: off
  react/prop-types: off # Use Flow instead
  react/no-unused-prop-types: off # See https://github.com/yannickcr/eslint-plugin-react/issues/811
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  no-underscore-dangle: off
  react/sort-comp:
    - error
    - order:
        - type-annotations
        - static-methods
        - lifecycle
        - everything-else
        - render
  no-console: off
env:
  browser: true
  jasmine: true
