# Docker compose YAML file
# Documentation: https://docs.docker.com/compose/compose-file/

version: "3"

services:
  neo4j:
    build: ./neo4j
    ports:
      - "7475:7474" # HTTPS host:container
      - "7688:7687" # BOLT host:container
    env_file: secrets/.env
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/conf:/var/lib/neo4j/conf

  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432" # host:container
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: secrets/.env
    command:
      - /backend/wait-for-postgres.sh
      - postgres
      - --
      - python
      - /backend/manage.py
      - runserver
      - 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8002:8000 # host:container
    depends_on:
      - neo4j
      - postgres

  frontend:
    build: ./frontend
    command: ["yarn", "start"]
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3002:3000 # host:container
    depends_on:
      - backend
