# Docker compose YAML file
# Documentation: https://docs.docker.com/compose/compose-file/

version: "3"

services:
  neo4j:
    build: ./neo4j
    ports:
      - "7475:7474" # HTTPS host:container
      - "7688:7687" # BOLT host:container
    environment:
      - NEO4J_AUTH=none # WARNING: Disable authentication in development
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import

  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432" # host:container
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    command:
      - /backend/tcp-port-wait.sh
      - postgres
      - "5432"
      - python
      - /backend/manage.py
      - runserver
      - 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8001:8000 # host:container
    depends_on:
      - neo4j
      - postgres

  frontend:
    build: ./frontend
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3001:3000 # host:container
    depends_on:
      - backend
