name: base
channels:
  - defaults
dependencies:
  - anaconda
  - pip
  - psycopg2 # connects to Postgres
  - pytest
  - pip:
      - neo4j
      - django==3.*
      - djangorestframework
      - django-cors-headers
      - docopt
      - ptvsd
      - pudb
      - schema # validates Python structures
