name: base
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.2.2
  - psycopg2 # connects to Postgres
  - pytest
  - pip:
      - neo4j
      - django==3.*
      - djangorestframework
      - django-cors-headers
      - docopt
      - ptvsd
      - pudb
      - schema # validates Python structures
